-- ==========================================================
-- One-shot activation for web notifications (message + payment)
-- ==========================================================
-- Replace placeholders:
--   <VERCEL_APP_URL>             e.g. https://mykahfi-web.vercel.app
--   <SUPABASE_WEBHOOK_SECRET>    must match env SUPABASE_WEBHOOK_SECRET in Vercel
--   <SUPABASE_SERVICE_ROLE_KEY>  should match env SUPABASE_SERVICE_ROLE_KEY in Vercel
--
-- This script DOES NOT alter existing table structures.
-- It only creates a new message table and creates triggers.

-- 1) Dedicated message table for web
create table if not exists public.user_messages_web (
  id bigint generated by default as identity primary key,
  nis text not null,
  message_text text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_messages_web_nis_active_created_at
  on public.user_messages_web (nis, is_active, created_at desc);

create or replace function public.get_latest_user_message_for_dashboard(p_nis text)
returns table (
  message_text text,
  created_at timestamptz
)
language sql
stable
as $$
  select
    m.message_text,
    m.created_at
  from public.user_messages_web m
  where m.nis = p_nis
    and m.is_active = true
    and nullif(btrim(m.message_text), '') is not null
  order by m.created_at desc, m.id desc
  limit 1;
$$;

-- 2) Disable old trigger path from users.msg_app to avoid duplicate delivery
drop trigger if exists on_users_msg_app_changed on public.users;

-- 3) Message triggers from new table -> /api/push/notify-message
drop trigger if exists on_user_messages_web_inserted on public.user_messages_web;
drop trigger if exists on_user_messages_web_updated on public.user_messages_web;

create trigger on_user_messages_web_inserted
after insert on public.user_messages_web
for each row
when (
  new.is_active = true
  and nullif(btrim(new.message_text), '') is not null
)
execute function supabase_functions.http_request(
  '<VERCEL_APP_URL>/api/push/notify-message',
  'POST',
  format(
    '{"Content-Type":"application/json","x-webhook-secret":"%s","Authorization":"Bearer %s"}',
    '<SUPABASE_WEBHOOK_SECRET>',
    '<SUPABASE_SERVICE_ROLE_KEY>'
  ),
  '{}',
  '5000'
);

create trigger on_user_messages_web_updated
after update of message_text, is_active on public.user_messages_web
for each row
when (
  new.is_active = true
  and nullif(btrim(new.message_text), '') is not null
  and (
    new.message_text is distinct from old.message_text
    or new.is_active is distinct from old.is_active
  )
)
execute function supabase_functions.http_request(
  '<VERCEL_APP_URL>/api/push/notify-message',
  'POST',
  format(
    '{"Content-Type":"application/json","x-webhook-secret":"%s","Authorization":"Bearer %s"}',
    '<SUPABASE_WEBHOOK_SECRET>',
    '<SUPABASE_SERVICE_ROLE_KEY>'
  ),
  '{}',
  '5000'
);

-- 4) Payment trigger -> /api/push/notify-payment
drop trigger if exists on_payment_received on public.bpi_sql_webhook_spb;

create trigger on_payment_received
after insert on public.bpi_sql_webhook_spb
for each row
execute function supabase_functions.http_request(
  '<VERCEL_APP_URL>/api/push/notify-payment',
  'POST',
  format(
    '{"Content-Type":"application/json","x-webhook-secret":"%s","Authorization":"Bearer %s"}',
    '<SUPABASE_WEBHOOK_SECRET>',
    '<SUPABASE_SERVICE_ROLE_KEY>'
  ),
  '{}',
  '5000'
);
