-- =============================================
-- MyKahfi Web - Database Tables (OneSignal Push)
-- Execute on Supabase SQL Editor
-- =============================================

-- Table: user_devices_web
-- Stores web device/subscription info for push notifications
create table if not exists public.user_devices_web (
  id bigint generated by default as identity primary key,
  nis text not null,
  onesignal_subscription_id text not null,
  external_id text not null,
  platform text not null check (platform in ('ios_web', 'android_web', 'desktop_web')),
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_user_devices_web_subscription
  on public.user_devices_web (onesignal_subscription_id, platform);
create index if not exists idx_user_devices_web_nis
  on public.user_devices_web (nis);

-- Table: notification_logs
-- Logs every push notification attempt for auditing
create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  nis text not null,
  event_type text not null check (event_type in ('payment', 'message')),
  provider text not null default 'onesignal',
  status text not null check (status in ('queued', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_logs_nis_created_at
  on public.notification_logs (nis, created_at desc);
create index if not exists idx_notification_logs_status
  on public.notification_logs (status);

-- Table: user_login_audit (if not exists from Android project)
-- Audit trail for login events across platforms
create table if not exists public.user_login_audit (
  id bigint generated by default as identity primary key,
  nis text not null,
  login_at timestamptz not null default now(),
  device_name text,
  device_sdk integer,
  app_version text,
  login_source text check (login_source in ('android_app', 'web_pwa', 'web_browser'))
);

create index if not exists idx_user_login_audit_nis_login_at
  on public.user_login_audit (nis, login_at desc);

-- Optional performance indexes for legacy dashboard table (if exists)
do $$
begin
  if to_regclass('public.transactions') is not null then
    execute 'create index if not exists idx_transactions_nis_tgl_trx
      on public.transactions (nis, tgl_trx desc)';
    execute 'create index if not exists idx_transactions_nis_bulan
      on public.transactions (nis, bulan)';
  end if;
end
$$;

-- Webhook payment table optimization (dashboard egress minimization)
create index if not exists idx_bpi_webhook_spb_nis_sortasi_tgltrx
  on public.bpi_sql_webhook_spb (nis, sortasi, tgltrx desc);

-- Returns latest payment row per academic sortasi (AGU..JUN) for one NIS.
create or replace function public.get_latest_monthly_payments_for_dashboard(p_nis text)
returns table (
  idtrx bigint,
  nominal bigint,
  tgltrx timestamptz,
  jenjang text,
  sortasi smallint
)
language sql
stable
as $$
  select distinct on (t.sortasi)
    t.idtrx,
    t.nominal,
    t.tgltrx,
    t.jenjang,
    t.sortasi
  from public.bpi_sql_webhook_spb t
  where t.nis = p_nis
    and t.sortasi between 2 and 12
  order by t.sortasi, t.tgltrx desc, t.idtrx desc;
$$;
