-- Create dedicated web message table without modifying existing tables.

create table if not exists public.user_messages_web (
  id bigint generated by default as identity primary key,
  nis text not null,
  message_text text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_messages_web_nis_active_created_at
  on public.user_messages_web (nis, is_active, created_at desc);

create or replace function public.get_latest_user_message_for_dashboard(p_nis text)
returns table (
  message_text text,
  created_at timestamptz
)
language sql
stable
as $$
  select
    m.message_text,
    m.created_at
  from public.user_messages_web m
  where m.nis = p_nis
    and m.is_active = true
    and nullif(btrim(m.message_text), '') is not null
  order by m.created_at desc, m.id desc
  limit 1;
$$;
